spring:
  application:
    name: CONFIG-DEFAULT
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registery: true
    register-with-eureka: true #by default is already true, but for my understanding
    service-url:
      defaultZone: http://localhost:8761/eureka #eureka service registry port
